### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by aliang888** [yuhonyon/svg2geojson#2]
ReferenceError: primordials is not defined
    at fs.js:47:5
    at req_ (C:\Users\Administrator\Desktop\svg2geojson\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\Administrator\Desktop\svg2geojson\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\svg2geojson\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)

**Comment by Lancer724** [comment]
我的是node版本不兼容，卸载重装一个11.15.0就正常运行了
